name: build kernel
on:
  workflow_call:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Update dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential bc flex bison libncurses5-dev libssl-dev git ccache python3 libtinfo6
          sudo rm -rf /usr/bin/python
          sudo ln -s /usr/bin/python3 /usr/bin/python
          python --version
          
      - name: Checkout Repo
        uses: actions/checkout@v4
        
      - name: List toolchain directories
        run: |
          ls -la toolchain/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/bin/
          ls -la toolchain/llvm-arm-toolchain-ship/10.0/bin/

      - name: Install gcc and clang
        run: |
          git clone https://github.com/LineageOS/android_prebuilts_gcc_linux-x86_aarch64_aarch64-linux-android-4.9 toolchain/gcc/linux-x86/aarch64/aarch64-linux-android-4.9
          git clone https://github.com/proprietary-stuff/llvm-arm-toolchain-ship-10.0 toolchain/llvm-arm-toolchain-ship/10.0

      - name: Fix line endings for Kconfig files
        run: |
          find . -name "*.Kconfig" -exec dos2unix {} \;
      
      - name: Build kernel
        run: |
          args="-j$(nproc --all) O=out ARCH=arm64 CLANG_TRIPLE=aarch64-linux-gnu- CROSS_COMPILE=$(pwd)/toolchain/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/bin/aarch64-linux-android- REAL_CC=$(pwd)/toolchain/llvm-arm-toolchain-ship/10.0/bin/clang"
          export DTC_EXT=dtc
          export LLVM=1
          export LLVM_IAS=1
          make ${args} vendor/gts7xlwifi_eur_open_defconfig
          make ${args} V=1

      - name: Build AK3
        run: |
          git clone https://github.com/CCCC-L/anyKernel3 releases
          sed -i "s/{branch}/${{ github.ref_name }}/" releases/anykernel.sh
          rm -rf releases/.git
          mv out/arch/arm64/boot/Image releases

      - name: Upload boot
        uses: actions/upload-artifact@v4
        with:
          name: T970-kernel-${{ github.ref_name }}
          path: releases
